CXX = g++
CXXFLAGS = -Wall -Wextra -Werror -std=c++17 -g -I./include -I/opt/homebrew/include
LDFLAGS = -L/opt/homebrew/lib -lgtest -lgtest_main -lpthread

OBJDIR = obj
BINDIR = bin

$(shell mkdir -p $(OBJDIR))
$(shell mkdir -p $(BINDIR))

all: string_utils teststrutils

string_utils: $(OBJDIR)/StringUtils.o
	$(CXX) -o $(BINDIR)/$@ $^ $(LDFLAGS)

teststrutils: $(OBJDIR)/StringUtils.o $(OBJDIR)/StringUtilsTest.o
	$(CXX) -o $(BINDIR)/$@ $^ $(LDFLAGS)
	./$(BINDIR)/$@

$(OBJDIR)/%.o: src/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(OBJDIR)/%.o: testsrc/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -rf $(OBJDIR) $(BINDIR)

.PHONY: all clean